# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  configurationVersion: 0.2.0
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: "Pwsh"
      directives:
        description: Install PowerShell 7
        allowPrerelease: true
      settings:
        id: Microsoft.PowerShell
        source: winget
        uselatest: true

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: "Code"
      directives:
        description: Install VisualStudio Code
        allowPrerelease: true
        uselatest: true
      settings:
        id: Microsoft.VisualStudioCode
        source: winget
        uselatest: true

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: "Terminal"
      directives:
        description: Install Windows Terminal
        allowPrerelease: true
      settings:
        id: Microsoft.WindowsTerminal
        source: winget
        uselatest: true

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: "Git"
      directives:
        description: Install Git
        allowPrerelease: true
        uselatest: true
      settings:
        id: Git.Git
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: "Chrome"
      directives:
        description: Install Google Chrome
        allowPrerelease: true
      settings:
        id: Google.Chrome
        source: winget
        uselatest: true

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: "DotNet SDK 8"
      directives:
        description: Install DotNet SDK 8
        allowPrerelease: true
      settings:
        id: Microsoft.DotNet.SDK.8
        source: winget
        uselatest: true

    - resource: Microsoft.Windows.Developer/HideFileExtensions
      directives:
        description: Hide file extensions
        allowPrerelease: true
      settings:
        Ensure: Absent

    - resource: ComputerManagementDsc/WindowsCapability
      id: opensshCapability
      directives:
        description: Remove OpenSSH Client Capability
        allowPrerelease: true
      settings:
        Name: OpenSSH.Client~~~~0.0.1.0
        Ensure: Absent

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: OpenSSH Client
      dependsOn:
        - opensshCapability
      directives:
        description: Install OpenSSH Client
        allowPrerelease: true
      settings:
        id: Microsoft.OpenSSH.Beta
        source: winget
        uselatest: true

    - resource: PSDscResources/WindowsOptionalFeature
      id: optionalFeatureHyperV
      directives:
        description: Enable Hyper-V
        allowPrerelease: false
      settings:
        Name: Microsoft-Hyper-V-All
        Ensure: Present

    - resource: PSDscResources/WindowsOptionalFeature
      id: optionalFeatureContainers
      directives:
        description: Enable Containers
        allowPrerelease: false
      settings:
        Name: Containers
        Ensure: Present

    - resource: PSDscResources/WindowsOptionalFeature
      id: optionalFeatureWSL
      dependsOn:
        - optionalFeatureHyperV
      directives:
        description: Enable WSL
        allowPrerelease: false
      settings:
        Name: Microsoft-Windows-Subsystem-Linux
        Ensure: Present

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: "Docker Desktop"
      dependsOn:
        - optionalFeatureWSL
      directives:
        description: Install Docker Desktop
        allowPrerelease: true
      settings:
        id: Docker.DockerDesktop
        source: winget
        uselatest: true

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: "WSL Ubuntu"
      dependsOn:
        - optionalFeatureWSL
      directives:
        description: Install WSL Ubuntu
        allowPrerelease: true
      settings:
        id: Canonical.Ubuntu.2204
        source: winget
        uselatest: true
